_BASE_: "Base-SOLOv2.yaml"
MODEL:
  # WEIGHTS: "/home/lahen/detectron2/AdelaiDet/training_dir/SOLOv2_R101_3x/model_0019999.pth"
  RESNETS:
    DEPTH: 101
SOLVER:
  STEPS: (40000, 70000)
  MAX_ITER: 100000
  IMS_PER_BATCH: 4
DATASETS:
  TRAIN: ("surgery_train2",)
  TEST: ("surgery_val2",)
INPUT:
  MIN_SIZE_TRAIN: (512,)
  MAX_SIZE_TRAIN: 512
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 512
TEST: 
  AUG:
    ENABLED: True
    MIN_SIZES: (512,)
    MAX_SIZE: 512
    FLIP: False
