_BASE_: "Base-SOLOv2.yaml"
MODEL:
  # WEIGHTS: '/home/lahen/detectron2/AdelaiDet/SOLOv2_R50_3x.pth'
  RESNETS:
    DEPTH: 50
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
  IMS_PER_BATCH: 4
  CHECKPOINT_PERIOD: 1000
DATASETS:
  TRAIN: ("surgery_train2",)
  TEST: ("surgery_val2",)
